name: Docs build CI(Sphinx)
on:
  push:
    branches: [ "v0.1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        pip install -U Sphinx
        pip install --user -r requirements.txt
    - name: Build HTML
      run: make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
